//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridgeClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int stockId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> quantity { get; set; }
        public string batchCode { get; set; }
        public Nullable<decimal> purchasePrice { get; set; }
        public Nullable<decimal> sellingPrice { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
